### PR TITLE
c9s: Pull in latest bootc/ostree

### PR DESCRIPTION
**Pull request by cgwalters**
On general principle, but specifically to enable transient root.

### CODE REVIEW

**Comment by cgwalters** [comment]
OK, whee.  I had to do like 8 clicks through the rhtap logs to find the failing job run here, and all *that* gave me was a URL to a testing farm artifact :cry: But digging into *that* shows the failure is

```
TASK [assert] ******************************************************************
fatal: [guest]: FAILED! => changed=false 
  assertion: result_list_boots.stdout_lines | length > 1
  evaluated_to: false
  msg: NO journald persistent logging configured
```

which is a known unrelated regression, so I'm clicking merge.

**Comment by cgwalters** [comment]
Some stamp please

**Comment by cgwalters** [comment]
Integration test failures are tracked at https://github.com/CentOS/centos-bootc/issues/354 and are unrelated to this PR

**Review by bcrochet — APPROVED** [review]
/lgtm

**Comment by cgwalters** [comment]
cc @sallyom @rhatdan

**Pull request merged**
