### PR TITLE
docs: Remove workarounds from example.ks

### PR DESCRIPTION
**Pull request by poncovka**
The partitioning defined in the example kickstart file suggests that the
installer supports hybrid boot. That's misleading and not true. Let's use
the `reqpart` kickstart command to automatically create partitions required
by the detected platform instead of creating all of them for all platforms.

**Note:** The `reqpart` command doesn't work with `bootloader --location=none` or
`bootloader --disabled`, so this change depends on the installer's support
for bootupd.

**Depends on:** https://github.com/rhinstaller/anaconda/pull/5298

### CODE REVIEW

**Comment by rhatdan** [comment]
@cgwalters Thoughts?

**Comment by cgwalters** [comment]
I was thinking we'd merge this after an Anaconda ISO was generated; looks like
https://src.fedoraproject.org/rpms/anaconda/blob/rawhide/f/anaconda.spec#_476
just happened and should probably be in https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/BaseOS/x86_64/iso/
so we should give that a spin

**Comment by cgwalters** [comment]
Gah, the trailing whitespace check is annoying

**Comment by lmilbaum** [comment]
> Gah, the trailing whitespace check is annoying

:-) It is. 
Few options:
1. Install pre-commit locally. It will report the error before you commit.
2. Disable this specific check. The issue is that it will apply to all files in the repo. GitHub shows a red sign when it is missing.
3. Use IDE plugin which adds the white space automatically when saving the file

**Comment by poncovka** [comment]
Updated. I run locally `pre-commit run --all-files` and it passed, so hopefully, it is fine now.

**Review by sallyom — APPROVED** [review]
pre-commit green, 
LGTM

**Pull request merged**
