### PR TITLE
tier-0: bootc is now in c9s

### PR DESCRIPTION
**Pull request by cgwalters**
So drop the conditional.

### CODE REVIEW

**Review by vrothberg — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
Is the test blowing up caused by an out of date repo?

**Comment by cgwalters** [comment]
it's https://github.com/CentOS/centos-bootc/issues/124 which should be fixed tomorrow we hope

**Pull request merged**
