### PR TITLE
tier-0: bootc is only in eln

### PR DESCRIPTION
**Pull request by cgwalters**
Prep for building with non-stream9 distros.

(TODO: add a dedicated variable for this at the toplevel)

### CODE REVIEW

**Comment by cgwalters** [comment]
Hooray, CI is working again - someone just needs to stamp this.

**Review by runcom — APPROVED** [review]

**Comment by runcom** [comment]
seems like I have no write access :P

**Review by rhatdan — APPROVED** [review]
LGTM

**Pull request merged**
