### PR TITLE
fedora-bootc: Bump to latest

### PR DESCRIPTION
**Pull request by cgwalters**
In particular this pulls in `toolbox`.

### CODE REVIEW

**Comment by cgwalters** [comment]
> error: Installing packages: Packages not found: NetworkManager-team, runc, teamd

- https://gitlab.com/fedora/bootc/base-images/-/merge_requests/19
- https://gitlab.com/fedora/bootc/base-images/-/merge_requests/18
-

**Comment by henrywang** [comment]
`centos-bootc-config.json` needs update. I pushed to ` cgwalters:bump-fedora-bootc` branch, but it's blocked by `ERROR: Permission to cgwalters/centos-bootc.git denied to henrywang.` Adding me into group or this repo should fix the permission issue. Thanks.

**Comment by cgwalters** [comment]
@henrywang Thanks for looking; I don't have permissions to add you, but I think the plan is to migrate to https://gitlab.com/redhat/centos-stream/containers/bootc which...hmm, perhaps I just need to do this PR over there

**Comment by cgwalters** [comment]
:arrow_right: https://gitlab.com/redhat/centos-stream/containers/bootc/-/merge_requests/2

**Pull request closed without merging**
