### PR TITLE
Add opt-usrlocal: root

### PR DESCRIPTION
**Pull request by cgwalters**
We want content lifecycled with the image.

Closes: https://github.com/CentOS/centos-bootc/issues/393

### CODE REVIEW

**Comment by cgwalters** [comment]
Blocks on https://github.com/osbuild/bootc-image-builder/issues/276

**Comment by cgwalters** [comment]
I think we don't need to block on the konflux presubmits; we clearly want it to work, but this builds as expected via GHA and we can also debug those post-submit.

**Review by jlebon — APPROVED** [review]
Let's do it!

**Review by mrguitar — APPROVED** [review]
LGTM

**Review by jeckersb — APPROVED** [review]

**Comment by cgwalters** [comment]
This makes it so that `/opt` and `/usr/local` are plain directories in this image, and not symlinks into `/var`.  This means they're immutable directories and the content is expected to come from the container image, and not be machine-local state (in `/var`).

**Pull request merged**
