### PR TITLE
Don't trigger the pull request pipelines if docs files were changed

### PR DESCRIPTION
**Pull request by lmilbaum**
I still think that extracting the docs folder to its own repository will simplify the CI/CD code.

### CODE REVIEW

**Review by vrothberg — APPROVED** [review]
LGTM

**Review by cgwalters — APPROVED** [review]

**Comment by cgwalters** [comment]
Maybe we should just split out the docs into a separate git repo.  The main reason I didn't try to start that now is creating new git repositories here feels like a bit of a speed bump.  Gets into the larger question of whether we should be on gitlab instead (again).

**Comment by lmilbaum** [comment]
> Maybe we should just split out the docs into a separate git repo. The main reason I didn't try to start that now is creating new git repositories here feels like a bit of a speed bump. Gets into the larger question of whether we should be on gitlab instead (again).

We could migrate to gitlab although the Konflux support has issues (for example: pipelines not triggered from a forked MR). The second thing is that github pages are tied to github so we might want to consider migrating to gitlab pages as well.

**Pull request merged**
