### PR TITLE
Drop fedora-bootc:eln image

### PR DESCRIPTION
**Pull request by cgwalters**
In order to streamline the focus, let's drop fedora-bootc:eln.

- We want to be moving container builds into upstream distributions anyways
- Building two containers from one git repository is awkward in Tekton

### CODE REVIEW

**Review by rhatdan — APPROVED** [review]
LGTM

**Review by rhatdan — APPROVED** [review]

**Comment by shi2wei3** [comment]
The test failure in centos-bootc-integration-test is irrelevant to this PR, it's about the journal log persistent issue.

**Comment by cgwalters** [comment]
When we do this, we will also need to (manually) prune all the images, including e.g. https://gitlab.com/bootc-org/podman-bootc-cli/-/issues/2#note_1793721536

**Comment by cgwalters** [comment]
ping @lmilbaum - I know you're on a bunch of things, but if you can briefly describe the steps you see as necessary I can take a look at it.  Is it basically pruning the RHTAP infra?

**Comment by cgwalters** [comment]
Split off https://github.com/CentOS/centos-bootc/pull/380 which I believe we can trivially merge now

**Comment by rhatdan** [comment]
@cgwalters is this still relavent or should it be closed?

**Comment by cgwalters** [comment]
I think this is still relevant.  @lmilbaum you originally had concerns, can you clarify?

**Review by lmilbaum — APPROVED** [review]

**Pull request merged**
